service: hopeisapp
useDotenv: true
plugins:
  - serverless-dotenv-plugin
  - serverless-offline

package:
  individually: false
  patterns:
    - '!test/**'
    - '!*.md'
    - '!**.ts'
    - '!src/**'
    - '!functions/**'

provider:
  name: aws
  stage: ${opt:stage, "dev"}
  region: ap-southeast-1
  runtime: nodejs20.x
  memorySize: 512
  timeout: 10
  architecture: x86_64
  deploymentMethod: direct
  cfnRole: arn:aws:iam::907877978309:role/hopeisapp-cloudformation-deployment-role
  environment:
    Project: hopeisapp
    Environment: ${sls:stage}
  stackTags:
    Project: hopeisapp
    Environment: ${sls:stage}
  deploymentBucket:
    name: hopeisapp-sls-deployment
  apiName: ${self:service}-api-${sls:stage}
  apiGateway:
    apiKeys:
      - ${self:service}-apikey-${sls:stage}
    usagePlan: ${self:custom.usagePlans.${sls:stage}}

custom:
  crons:
    dev:
      rate: rate(6 hours)
    uat:
      rate: rate(6 hours)
    prod:
      rate: rate(1 hour)
  usagePlans:
    dev:
      quota:
        limit: 5000
        period: MONTH
      throttle:
        burstLimit: 200
        rateLimit: 100
    uat:
      quota:
        limit: 5000
        period: MONTH
      throttle:
        burstLimit: 200
        rateLimit: 100
    prod:
      quota:
        limit: 50000
        period: MONTH
      throttle:
        burstLimit: 2000
        rateLimit: 1000
  cors:
    origins:
      dev:
        - "http://localhost:4200"
        - "http://localhost:3000"
        - "http://dev.hopeis.us.s3-website-ap-southeast-1.amazonaws.com"
        - "https://dev.hopeis.us"
      uat:
        - "https://uat.hopeis.us"
      prod:
        - "https://www.hopeis.us"
        - "https://hopeis.us"
    headers:
      - Content-Type
      - X-Amz-Date
      - Authorization
      - X-Api-Key
      - X-Amz-Security-Token
    allowCredentials: true  

functions:
  - ${file(sls-templates/data-function.yml)}
  - ${file(sls-templates/profiles-function.yml)}
  - ${file(sls-templates/quiz-results-function.yml)}
  - ${file(sls-templates/profile-activities-function.yml)}
  - ${file(sls-templates/me-function.yml)}
  - ${file(sls-templates/crons-function.yml)}