name: Angular Build

on:
  pull_request:
    branches: ["main"]

jobs:
  build:
    uses: ./.github/workflows/template-angular-build.yml
    with:
      environment: dev
    secrets: inherit
  deploy:
    name: Angular Deploy on Dev
    needs: ["build"]
    uses: ./.github/workflows/template-angular-deploy.yml
    with:
      environment: dev
      buildPath: dist/frontend
    secrets: inherit