on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      buildPath:
        required: true
        type: string

jobs:
  Deploy-S3:
    name: Deploy Build Package to S3 on ${{ inputs.environment }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    if: github.job.needs != null
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/download-artifact@master
        with:
          name: dist
          path: frontend/dist
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-southeast-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Validate AWS CLI permission
        run: |
          aws s3 ls
      - name: Sync to S3
        run: aws s3 sync ${{ inputs.buildPath }} ${{ vars.CODE_BUCKET }}