name: Manual Full Deployment
on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        default: dev

jobs:
  ng-build:
    name: Angular build on ${{ inputs.environment }}
    uses: ./.github/workflows/tpl-angular-build.yml
    with:
      environment: ${{ inputs.environment }}
    secrets: inherit
  ng-deploy:
    name: Angular Deploy on ${{ inputs.environment }}
    needs: ["ng-build"]
    uses: ./.github/workflows/tpl-angular-deploy.yml
    with:
      environment: ${{ inputs.environment }}
    secrets: inherit
  
  sls-build:
    name: Serverless Framework Build on ${{ inputs.environment }}
    uses: ./.github/workflows/tpl-sls-build.yml
    with:
      environment: ${{ inputs.environment }}
    secrets: inherit
  sls-deploy:
    name: Serverless Framework Deploy on ${{ inputs.environment }}
    needs: ["sls-build"]
    uses: ./.github/workflows/tpl-sls-deploy.yml
    with:
      environment: ${{ inputs.environment }}
    secrets: inherit