name: Main Deployment

on:
  push:
    branches: ["main"]

jobs:
  ng-build:
    name: Angular build on Development
    uses: ./.github/workflows/tpl-angular-build.yml
    with:
      environment: dev
    secrets: inherit
  ng-deploy:
    name: Angular Deploy on Development
    needs: ["ng-build"]
    uses: ./.github/workflows/tpl-angular-deploy.yml
    with:
      environment: dev
    secrets: inherit

  sls-build:
    name: Serverless Framework Build on Dev
    uses: ./.github/workflows/tpl-sls-build.yml
    with:
      environment: dev
    secrets: inherit
  sls-deploy:
    name: Serverless Framework Deploy on Dev
    needs: ["sls-build"]
    uses: ./.github/workflows/tpl-sls-deploy.yml
    with:
      environment: dev
    secrets: inherit
