name: Serverless Framework on PR

on:
  pull_request:
    branches: ["main"]
    paths:
      - backend/**

jobs:
  build:
    name: Serverless Framework Build on Dev
    uses: ./.github/workflows/tpl-sls-build.yml
    with:
      environment: dev
    secrets: inherit