name: Angular Build on PR

on:
  pull_request:
    branches: ["main"]
    # paths:
    #   - frontend/**
    #   - .github

jobs:
  build:
    name: Angular build on Dev
    uses: ./.github/workflows/tpl-angular-build.yml
    with:
      environment: dev
    secrets: inherit
  deploy:
      name: Angular Deploy on Dev
      needs: ["build"]
      uses: ./.github/workflows/tpl-angular-deploy.yml
      with:
        environment: dev
      secrets: inherit